[package]
name = "tailray-bin"
version = "0.1.0"
edition = "2021"

[dependencies]
clipboard = "0.5"
env_logger = "0.9"
ksni = "0.2"
log = "0.4"
notify-rust = "4.5"
open = "2.1"
resvg = "0.22"
serde = "1.0"
serde_json = "1.0"
tiny-skia = "0.6"
usvg = "0.22"
which = "4.2"
