name: Build with Cargo

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get build dependencies
        run: |
          sudo apt install \
            pkg-config libdbus-1-dev libxcb1 \
            libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Build
        run: cargo build --verbose
